# GitHub Actions workflow to build and deploy Azure Function to existing infrastructure
name: Deploy Azure Function to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true

      # Azure CLI is pre-installed on GitHub runners; no need for azure/cli@v2
      - name: Check Azure CLI version
        run: az --version

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MyFunction/MyFunction/requirements.txt

      - name: Build Azure Function
        run: |
          cd MyFunction/MyFunction
          func azure functionapp publish ${{ secrets.AZURE_FUNCTIONAPP_NAME }} --build remote --python

      - name: Deploy infrastructure (optional)
        if: github.event_name == 'workflow_dispatch'
        run: |
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file infra/main.bicep \
            --parameters @infra/main.parameters.json

# Required secrets:
# - AZURE_CREDENTIALS: Output of `az ad sp create-for-rbac --sdk-auth` (JSON)
# - AZURE_FUNCTIONAPP_NAME: Name of the deployed Azure Function App
# - AZURE_RESOURCE_GROUP: Name of the resource group
