# GitHub Actions workflow to build and deploy Azure Function to existing infrastructure
name: Deploy Azure Function to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true

      # Azure CLI is pre-installed on GitHub runners; no need for azure/cli@v2
      - name: Check Azure CLI version
        run: az --version

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MyFunction/MyFunction/requirements.txt

      - name: Ensure Function App exists
        id: ensure-funcapp
        run: |
          set -e
          # Check if the Function App exists
          if az functionapp show --name "$AZURE_FUNCTIONAPP_NAME" --resource-group "$AZURE_RESOURCE_GROUP" 2>/dev/null; then
            echo "Function App exists."
          else
            echo "Function App does not exist. Creating..."
            # Find the app service plan in the resource group
            PLAN_NAME=$(az appservice plan list --resource-group "$AZURE_RESOURCE_GROUP" --query "[?kind=='functionapp'].name | [0]" -o tsv)
            if [ -z "$PLAN_NAME" ]; then
              echo "No app service plan found for function app. Exiting."
              exit 1
            fi
            # Create the Function App
            az functionapp create \
              --name "$AZURE_FUNCTIONAPP_NAME" \
              --resource-group "$AZURE_RESOURCE_GROUP" \
              --plan "$PLAN_NAME" \
              --storage-account $(az storage account list --resource-group "$AZURE_RESOURCE_GROUP" --query "[0].name" -o tsv) \
              --runtime python \
              --functions-version 4
          fi

      - name: Build Azure Function
        run: |
          cd MyFunction/MyFunction
          func azure functionapp publish ${{ secrets.AZURE_FUNCTIONAPP_NAME }} --build remote --python

      - name: Deploy infrastructure (optional)
        if: github.event_name == 'workflow_dispatch'
        run: |
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file infra/main.bicep \
            --parameters @infra/main.parameters.json

# Required secrets:
# - AZURE_CREDENTIALS: Output of `az ad sp create-for-rbac --sdk-auth` (JSON)
# - AZURE_FUNCTIONAPP_NAME: Name of the deployed Azure Function App
# - AZURE_RESOURCE_GROUP: Name of the resource group
